### ISSUE TITLE
Minor updates 

### ISSUE THREAD

**Issue by dreamos82** [dreamos82/chrome_parameters#115]
Few minor changes  needed in different parts: 

* Mention in the help the new behavior of chrome that it hide all the extension in the jigsaw button on the address bar, and that if the extension wants to be kept visible all the time needs to be pinned
*  Remove flattr button from the extension 
* Add a link to the github page website in the Help
* Typo in the help, First line of paragraph "What you can do with this extension"
*  Another typo in post_install.html line 18 (of source code)

**Comment by kushalsng** [comment]
Hello, I would like to contribute here.
