### ISSUE TITLE
Add possibility for chromium keyboard shortcut definition

### ISSUE THREAD

**Issue by siljuberg** [dreamos82/chrome_parameters#119]
As a user I would like to to add a keyboard shortcut to the extension by defining it in:
chrome://extensions/shortcuts

**Comment by dreamos82** [comment]
Thanks for the suggestion, is a very nice idea, i will have a look on how it can be implemented. 

https://developer.chrome.com/docs/extensions/reference/commands/  (i suppose it is what i will have to do to implement this feature)
