### ISSUE TITLE
Update ui component for Exporting

### ISSUE THREAD

**Issue by inuyasha82** [dreamos82/chrome_parameters#68]
Afer adding a new export option we need to update the behaviour of export button. 

A possible option is that when the user click on the export button, it will show the export options below other buttons using the same font as Create New Issue link. 

The idea is something similar to this screenshot (obviously it has to be improved)
<img width="394" alt="Screenshot 2019-10-25 at 11 14 02" src="https://user-images.githubusercontent.com/433308/67559162-aae63480-f718-11e9-9687-e6d458b52807.png">

If there are bette roptions i'm open to discussion.

**Comment by sonamdh1** [comment]
Can I give it a try?

**Comment by inuyasha82** [comment]
Yeah, sure! Just keep in mind that the screenshot was just to give an idea, but the style has to be improved :D (i.e. spacing and positioning).

**Comment by sonamdh1** [comment]
Sure.

**Comment by sonamdh1** [comment]
I have raised a PR, please review and let me know.

**Comment by inuyasha82** [comment]
Thanks, i'll review it this evening/tomorrow.

**Comment by sonamdh1** [comment]
Okay, sure.
