### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by inuyasha82** [dreamos82/chrome_parameters#76]
Since it is going to be available on firefox too with release of version 1.6 i'm wondering if the name should be changed with a new one. Or kept as it is, and the firefox version will be simply called: Fiirefox (url) parameter or whatever.

If anyone has ideas i'm open to suggestions!

**Comment by inuyasha82** [comment]
calling it Browser Parameters for now, until a new name is found.

**Comment by dreamos82** [comment]
Problem is i can't change the name of the extension for the chrome store. 

So probably they will be called Firefox Parameters and Chrome parameters, (and in the documentation referred as Browser Parameters)

**Comment by dreamos82** [comment]
Probably i'm not going to change the name of the repository, for the time being, so i'm going to close this issue for now.
