### ISSUE TITLE
Update urls to use the new repository address

### ISSUE THREAD

**Issue by inuyasha82** [dreamos82/chrome_parameters#92]
Files to be updated:

* post_install.html
* post_update.html

And check if there are other places in the codes where the old project url is used.

The new url is: https://github.com/dreamos82/chrome_parameters

**Comment by humanolaranja** [comment]
Can I get this one?

**Comment by inuyasha82** [comment]
Yeah sure, thank you!!!

I reviewed your PR, left a comment, with couple of places where to update the urls! 

Thanks again!
